# Generated by Django 5.2.7 on 2025-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0002_update_status_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('for_editing', 'For editing'), ('for_approval', 'For approval'), ('for_publishing', 'For publishing'), ('published', 'Published'), ('deleted', 'Deleted')], default='for_editing', max_length=32),
        ),
    ]
