# Generated by Django 6.0.1 on 2026-01-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0005_alter_contentpage_author'),
    ]

    operations = [
    ]
