# Generated by Django 6.0.1 on 2026-01-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0006_auto_20260129_0947'),
    ]

    operations = [
    ]
