# Generated by Django 6.0.1 on 2026-02-02 08:55
# Migration now empty - all fields already in 0001_initial

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0003_alter_contentitem_status'),
    ]

    operations = [
        # All AddField operations removed - fields already exist in 0001_initial
    ]

