# Generated by Django 6.0.1 on 2026-02-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0003_alter_contentitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='ar_marker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='chat_bot_allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='enable_badges',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='exclude_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='quiz',
            field=models.BooleanField(default=False),
        ),
    ]
