# Generated by Django 6.0.1 on 2026-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0008_contentitem_ar_marker_contentitem_chat_bot_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='text', max_length=50),
        ),
    ]
