# Generated by Django 6.0.2 on 2026-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0008_contentitem_ar_marker_contentitem_chat_bot_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='quiz_correct_answers',
            field=models.JSONField(blank=True, default=dict, help_text="Quiz correct answers: {1: 'a', 2: 'b', ...}"),
        ),
    ]
