# Generated by Django 6.0.2 on 2026-02-12 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0008_contentitem_ar_marker_contentitem_chat_bot_allow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('quiz', 'Quiz')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='quiz_correct_answers',
            field=models.JSONField(blank=True, default=dict, help_text="Quiz correct answers: {1: 'a', 2: 'b', ...}"),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Ordering index for the question within the quiz')),
                ('text', models.TextField(help_text='The question text')),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='contentmanagement.contentitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short label for the choice (e.g. 'A', 'B', 'C')", max_length=4)),
                ('text', models.TextField(help_text='The answer text')),
                ('is_correct', models.BooleanField(default=False, help_text='Whether this choice is the correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='contentmanagement.quizquestion')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
