# Generated by Django 6.0.1 on 2026-02-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0009_alter_contentitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from the approver about the approval or rejection'),
        ),
    ]
