# Generated by Django 6.0.2 on 2026-02-23 04:12

import apps.contentmanagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0009_alter_contentitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.contentmanagement.models.content_file_upload_to),
        ),
    ]
