# Generated by Django 6.0.2 on 2026-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0010_alter_contentitem_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='quiz_badges',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='quiz_correct_answers',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='quiz_length',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='quiz_number',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='trivia_questions',
            field=models.JSONField(blank=True, default=list, help_text='Array of trivia question objects for mobile clients'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('trivia', 'Trivia Questions')], default='text', max_length=50),
        ),
    ]
