"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# `base.py` lives in `config/settings/`, so go up three levels to reach
# the repository/project root (AGHAMazingQuestCMS).
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment for safety. These defaults are
# only suitable for local development; replace them in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-8i)k0@hetowp(8-+g6e222ejlkvdr44#8*7dg)f0m10m4*e63l",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety in production deployments. Set DJANGO_DEBUG=True
# in your development environment if you need debug mode locally.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# Hosts allowed to serve the app. Read from env, splitting on commas and
# stripping whitespace. If the env var is missing or doesn't include the
# machine's hostname (common in some container setups), append a sensible
# fallback (hostname + '.ts.net') so requests to the provided domain are
# accepted when no explicit env var is provided.
_raw_allowed = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,hosting-pc.tail013787.ts.net",
)
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]
try:
    _fallback = socket.gethostname() + ".ts.net"
    if _fallback and _fallback not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_fallback)
except Exception:
    # if socket fails for any reason, just continue with the parsed list
    pass


# Application definition

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Wagtail CMS
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail',

    # Wagtail dependencies
    'modelcluster',
    'taggit',

    # REST Framework
    'rest_framework',
    'corsheaders',

    # Your apps
    'apps.authentication',
    'apps.contentmanagement',
    'apps.usermanagement',
    'apps.analyticsmanagement',
]

MIDDLEWARE = [
    # CORS middleware should be placed as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Wagtail redirects middleware should be after CommonMiddleware
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'



# Database
# Support switching between sqlite, MySQL and PostgreSQL via environment variables.
# DB_ENGINE: 'sqlite' | 'mysql' (default when DEBUG is False) | 'postgres'/'postgresql'
# For local development (DEBUG=True) default to sqlite to avoid requiring a DB server.
default_db = 'sqlite' if DEBUG else 'mysql'
DB_ENGINE = os.environ.get('DB_ENGINE', default_db).lower()
if DB_ENGINE == 'sqlite':
    engine = 'django.db.backends.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': engine,
            'NAME': os.environ.get('DB_NAME', str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    if DB_ENGINE in ('mysql', 'mariadb'):
        try:
            import pymysql

            pymysql.install_as_MySQLdb()
        except Exception:
            # If PyMySQL is not available, let Django raise an import error later
            pass
        engine = 'django.db.backends.mysql'
    elif DB_ENGINE in ('postgres', 'postgresql'):
        engine = 'django.db.backends.postgresql'
    else:
        engine = DB_ENGINE

    DATABASES = {
        'default': {
            'ENGINE': engine,
            'NAME': os.environ.get('DB_NAME', 'aghamazing_db'),
            'USER': os.environ.get('DB_USER', 'admin'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'admin'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306' if engine.endswith('mysql') else '5432'),
            'OPTIONS': {
                # MySQL strict mode is recommended; leave empty for PostgreSQL
                **({'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"} if engine.endswith('mysql') else {}),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Where `collectstatic` will gather files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Additional locations Django will search for static files in development
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files uploaded by users
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sites framework (required by Wagtail)
SITE_ID = int(os.environ.get('DJANGO_SITE_ID', 1))

# Base URL for Wagtail admin (used in notifications and user bar links)
WAGTAILADMIN_BASE_URL = os.environ.get('WAGTAILADMIN_BASE_URL', 'http://localhost:8000')

# CORS (for React frontend running on localhost:3000)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]
CORS_ALLOW_CREDENTIALS = True

# Django REST Framework + Simple JWT configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# Simple JWT defaults: short access token, longer refresh token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}


# ---------- Security / production defaults
# When DEBUG is False, pick sensible secure defaults from environment variables.
# These defaults help pass `manage.py check --deploy` and are safe to override
# per-deployment via environment variables.
if not DEBUG:
    # Force SSL redirect in production unless explicitly disabled
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'

    # HSTS: one year by default. When testing set to a small value first.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'False') == 'True'

    # Cookies: mark secure so browsers only send them over HTTPS
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'True') == 'True'

    # SECRET_KEY should be set externally in production and be long/random.
    if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
        # Do not silently accept insecure keys in production — raise to fail fast
        raise RuntimeError('Insecure SECRET_KEY in production. Set DJANGO_SECRET_KEY environment variable to a secure value.')

    # If running behind a proxy/load-balancer that terminates SSL, set this header
    # Example: SECURE_PROXY_SSL_HEADER='HTTP_X_FORWARDED_PROTO,https'
    _proxy = os.environ.get('DJANGO_SECURE_PROXY_SSL_HEADER')
    if _proxy:
        try:
            header_name, header_value = _proxy.split(',', 1)
            SECURE_PROXY_SSL_HEADER = (header_name.strip(), header_value.strip())
        except Exception:
            # ignore malformed setting and proceed without proxy header
            pass

    # Ensure DEBUG is False in production
    DEBUG = False

