# Generated by Django 6.0.2 on 2026-02-23 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentmanagement', '0009_alter_contentitem_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('comment', 'Comment'), ('download', 'Download'), ('complete_quiz', 'Complete Quiz')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='contentmanagement.contentitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Engagement',
                'verbose_name_plural': 'Content Engagements',
                'indexes': [models.Index(fields=['content_item', 'action', '-timestamp'], name='analyticsma_content_2e4419_idx'), models.Index(fields=['timestamp'], name='analyticsma_timesta_57ed9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentViewTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='contentmanagement.contentitem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content View',
                'verbose_name_plural': 'Content Views',
                'indexes': [models.Index(fields=['content_item', '-viewed_at'], name='analyticsma_content_f12f2b_idx'), models.Index(fields=['viewed_at'], name='analyticsma_viewed__18bb0c_idx')],
            },
        ),
    ]
