"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# `base.py` lives in `config/settings/`, so go up three levels to reach
# the repository/root (AGHAMazingQuestCMS).
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment for safety. These defaults are
# only suitable for local development; replace them in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-8i)k0@hetowp(8-+g6e222ejlkvdr44#8*7dg)f0m10m4*e63l",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety in production deployments. Set DJANGO_DEBUG=True
# in your development environment if you need debug mode locally.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"  # Default to True for staging

# Hosts allowed to serve the app. Read from env, splitting on commas and
# stripping whitespace. If the env var is missing or doesn't include the
# machine's hostname (common in some container setups), append a sensible
# fallback (hostname + '.ts.net') so requests to the provided domain are
# accepted when no explicit env var is provided.
_raw_allowed = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,hosting-pc.tail013787.ts.net,0.0.0.0,[::],192.168.0.0/16,10.0.0.0/8,172.16.0.0/12",
)
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]
try:
    _fallback = socket.gethostname() + ".ts.net"
    if _fallback and _fallback not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_fallback)
        
    # Add local IP to allow access from local network
    local_ip = socket.gethostbyname(socket.gethostname())
    if local_ip and local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    # if socket fails for any reason, just continue with the parsed list
    pass


# Database
# Support switching between sqlite and PostgreSQL via environment variables.
# DB_ENGINE: 'sqlite' | 'postgres'/'postgresql' (default when DEBUG is False)
# For local development (DEBUG=True) default to sqlite to avoid requiring a DB server.
# Removed conditional logic - always use PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'aghamazing_db'),
        'USER': os.environ.get('DB_USER', 'admin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'password123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),  # Changed to 5432 for local PostgreSQL
        'OPTIONS': {
            # PostgreSQL specific options
            'sslmode': os.environ.get('DB_SSLMODE', 'prefer'),
        },
    }
}


# Application definition
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Add postgres contrib if using PostgreSQL
INSTALLED_APPS.append('django.contrib.postgres')

# Add REST Framework and other apps
INSTALLED_APPS.extend([
    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # API Documentation
    'drf_yasg',

    # Your apps
    'apps.authentication',
    'apps.contentmanagement',
    'apps.usermanagement',
    'apps.analyticsmanagement',
    'apps.mobilemanagement',  # Adding mobile management app
])

MIDDLEWARE = [
    # API optimization middleware should be first for performance measurement
    'middleware.api_optimization.APILoggerMiddleware',
    'middleware.api_optimization.MobileAppOptimizationMiddleware',
    'middleware.api_optimization.APIResponseFormatterMiddleware',
    
    # CORS middleware should be placed as high as possible
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Additional locations Django will search for static files in development
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Media files uploaded by users
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS (for React frontend and Flutter app)
# Read allowed origins from environment variable for flexibility.
# Default to common development values if not set.
CORS_ALLOWED_ORIGIN_REGEXES = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://[::1]:3000',      # IPv6 localhost
    'http://192.168.0.1:3000',  # Common router IP
    'http://192.168.1.1:3000',  # Another common router IP
    'http://10.0.0.1:3000',     # Private network
    'http://172.16.0.1:3000',   # Private network
    'http://172.19.91.23:3000',  # Staging environment IP for frontend
    'http://localhost:8080',  # Nginx proxy server
    'https://localhost:8080',  # Nginx proxy server (HTTPS)
    # Adding origins for Flutter app access
    'http://localhost:8000',  # Django development server (for Flutter app)
    'http://127.0.0.1:8000',  # IPv4 localhost (for Flutter app)
    # Adding the frontend port where it's actually running
    'http://localhost:3001',  # Frontend development server
    'http://127.0.0.1:3001',  # IPv4 localhost for frontend
]
CORS_ALLOW_CREDENTIALS = True
# You can override this with a comma-separated list in the environment variable
if os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES'):
    additional_origins = [origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES', '').split(',') if origin.strip()]
    CORS_ALLOWED_ORIGIN_REGEXES.extend(additional_origins)

# Allow all origins if CORS_ALLOWED_ORIGIN_REGEXES is not set (for development)
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# CSRF Trusted Origins for development
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',  # React development server
    'http://127.0.0.1:3000',  # IPv4 localhost
    'http://localhost:8000',  # Django development server
    'http://127.0.0.1:8000',  # IPv4 localhost
    'http://localhost:8081',  # Nginx proxy server
    'https://localhost:8081', # Nginx proxy server (HTTPS)
    'http://0.0.0.0:8081',    # Additional host for container access
    'http://127.0.0.1:8081',  # Additional host for local access
    # Adding the frontend port where it's actually running
    'http://localhost:3001',  # Frontend development server
    'http://127.0.0.1:3001',  # IPv4 localhost for frontend
]

# Add additional trusted origins from environment variable if set
# This is important for production/staging environments
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    additional_origins = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)
    
# Note: Browsers cache CORS preflight responses (OPTIONS) for 5-15 minutes by default.
# Use Vary: Origin header in responses to ensure proper caching behavior.
# Consider adding Cache-Control header with max-age directive if needed.

# Security settings for CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'X-CSRFTOKEN',
]

# Django REST Framework + Simple JWT configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    # Add throttling for mobile app API calls
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Simple JWT defaults: short access token, longer refresh token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  # Enable refresh token rotation
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'UPDATE_LAST_LOGIN': True,  # Update last login timestamp
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# ---------- Security / production defaults
# When STAGING_ENVIRONMENT is True, use relaxed security settings appropriate for staging
STAGING_ENVIRONMENT = os.environ.get('STAGING_ENVIRONMENT', 'False') == 'True'

if STAGING_ENVIRONMENT:
    # Relaxed security for staging environment
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'
    SECURE_HSTS_SECONDS = 0  # Don't enforce HSTS in staging
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # Allow insecure cookies in staging (not recommended for production)
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False') == 'True'
elif not DEBUG:
    # Production security settings
    # Force SSL redirect in production unless explicitly disabled
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'

    # HSTS: one year by default. When testing set to a small value first.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'
    SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'False') == 'True'

    # Cookies: mark secure so browsers only send them over HTTPS
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'True') == 'True'

    # SECRET_KEY should be set externally in production and be long/random.
    if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
        # Do not silently accept insecure keys in production — raise to fail fast
        raise RuntimeError('Insecure SECRET_KEY in production. Set DJANGO_SECRET_KEY environment variable to a secure value.')

    # If running behind a proxy/load-balancer that terminates SSL, set this header
    # Example: SECURE_PROXY_SSL_HEADER='HTTP_X_FORWARDED_PROTO,https'
    _proxy = os.environ.get('DJANGO_SECURE_PROXY_SSL_HEADER')
    if _proxy:
        try:
            header_name, header_value = _proxy.split(',', 1)
            SECURE_PROXY_SSL_HEADER = (header_name.strip(), header_value.strip())
        except Exception:
            # ignore malformed setting and proceed without proxy header
            pass

    # Ensure DEBUG is False in production
    DEBUG = False