"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import socket
from datetime import timedelta
import dj_database_url  # Import for parsing DATABASE_URL
from urllib.parse import urlparse, parse_qsl
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# `base.py` lives in `config/settings/`, so go up three levels to reach
# the repository/root (AGHAMazingQuestCMS).
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment for safety. These defaults are
# only suitable for local development; replace them in production.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-8i)k0@hetowp(8-+g6e222ejlkvdr44#8*7dg)f0m10m4*e63l",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety in production deployments. Set DJANGO_DEBUG=True
# in your development environment if you need debug mode locally.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"  # Default to True for staging

# Hosts allowed to serve the app. Read from env, splitting on commas and
# stripping whitespace. Default to common development values.
_raw_allowed = os.environ.get(
    "DJANGO_ALLOWED_HOSTS",
    "localhost,127.0.0.1,0.0.0.0",
)
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]

# Add local IP to allow access from local network
try:
    hostname = socket.gethostname()
    local_ip = socket.gethostbyname(hostname)
    if local_ip and local_ip not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(local_ip)
except Exception:
    # if socket fails for any reason, just continue with the parsed list
    pass

# Database
# Parse DATABASE_URL if it exists
if os.environ.get('DATABASE_URL'):
    tmpPostgres = urlparse(os.environ.get('DATABASE_URL'))

    # Extract and validate components
    port = tmpPostgres.port or 5432
    options = dict(parse_qsl(tmpPostgres.query))

    # Only validate port and sslmode if using Neon (contains neon.tech)
    if 'neon.tech' in tmpPostgres.hostname:
        if port != 5432:
            print(f"WARNING: Neon database should use port 5432, got {port}. This may cause connection issues.")

        if options.get('sslmode') != 'require':
            print("WARNING: Neon database requires sslmode=require. This may cause connection issues.")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.replace('/', ''),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': port,
            'OPTIONS': options,
        }
    }
else:
    # Fallback to manual configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'aghamazing_db'),
            'USER': os.environ.get('DB_USER', 'admin'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'password123'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                # Require SSL for production environments
                'sslmode': os.environ.get('DB_SSLMODE', 'require'),
                # TCP keepalive settings for stable connections
                'keepalives': 1,
                'keepalives_idle': 30,
                'keepalives_interval': 10,
                'keepalives_count': 5,
                # Additional settings for Neon compatibility
                'connect_timeout': 15,
            },
        }
    }




# Application definition
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Add postgres contrib if using PostgreSQL
INSTALLED_APPS.append('django.contrib.postgres')

# Add REST Framework and other apps
INSTALLED_APPS.extend([
    # REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # API Documentation
    'drf_yasg',

    # Your apps
    'apps.authentication',
    'apps.contentmanagement',
    'apps.usermanagement',
    'apps.analyticsmanagement',
    'apps.mobilemanagement',
    'apps.notificationsmanagement',
])

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',  # Required for admin
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Additional locations Django will search for static files in development
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

# Media files uploaded by users
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS (for React frontend and Flutter app)
# Read allowed origins from environment variable for flexibility.
# Default to common development values if not set.
CORS_ALLOWED_ORIGIN_REGEXES = [
    'http://100.93.255.84:3000',  # Tailscale IP
    'https://100.93.255.84:3000',  # Tailscale IP (HTTPS)
    'http://100.93.255.84:8000',  # Tailscale IP backend
    'https://100.93.255.84:8000', # Tailscale IP backend (HTTPS)
]
CORS_ALLOW_CREDENTIALS = True
# You can override this with a comma-separated list in the environment variable
if os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES'):
    additional_origins = [origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGIN_REGEXES', '').split(',') if origin.strip()]
    CORS_ALLOWED_ORIGIN_REGEXES.extend(additional_origins)

# Allow all origins if CORS_ALLOWED_ORIGIN_REGEXES is not set (for development)
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# CSRF Trusted Origins - Tailscale IP only
CSRF_TRUSTED_ORIGINS = [
    'http://100.93.255.84:3000',  # Tailscale IP frontend
    'https://100.93.255.84:3000', # Tailscale IP frontend (HTTPS)
    'http://100.93.255.84:8000',  # Tailscale IP backend
    'https://100.93.255.84:8000', # Tailscale IP backend (HTTPS)
]

# Add additional trusted origins from environment variable if set
# This is important for production/staging environments
if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    additional_origins = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
    CSRF_TRUSTED_ORIGINS.extend(additional_origins)


# Django REST Framework + Simple JWT configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
    # Add throttling for mobile app API calls
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Simple JWT defaults: short access token, longer refresh token
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,  # Enable refresh token rotation
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist old refresh tokens
    'UPDATE_LAST_LOGIN': True,  # Update last login timestamp
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# ---------- Security / production defaults
# For local development, we'll keep security settings reasonable but not overly strict
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False') == 'True'

# Additional security settings
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'False') == 'True'
X_FRAME_OPTIONS = os.environ.get('DJANGO_X_FRAME_OPTIONS', 'DENY')

# Content Security Policy
CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]
CSP_IMG_SRC = ["'self'", "data:"]
CSP_FONT_SRC = ["'self'"]
CSP_CONNECT_SRC = ["'self'"]
CSP_OBJECT_SRC = ["'none'"]
CSP_BASE_URI = ["'self'"]
CSP_FORM_ACTION = ["'self'"]
CSP_FRAME_ANCESTORS = ["'none'"]

# SECRET_KEY should be set externally in production and be long/random.
if not SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
    # Do not silently accept insecure keys in production — raise to fail fast
    if not DEBUG:
        raise RuntimeError('Insecure SECRET_KEY in production. Set DJANGO_SECRET_KEY environment variable to a secure value.')